# Generated by Django 5.1.3 on 2025-02-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_userprofile_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_no",
            field=models.BigIntegerField(),
        ),
    ]
