# Generated by Django 5.1.3 on 2025-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendorsignup", "0002_remove_vendor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
