# Generated by Django 5.1.3 on 2025-02-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendorsignup", "0003_alter_vendor_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorproduct",
            name="vendor",
        ),
        migrations.AlterUniqueTogether(
            name="vendorproduct",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vendorproduct",
            name="products",
        ),
        migrations.DeleteModel(
            name="vendor",
        ),
        migrations.DeleteModel(
            name="vendorproduct",
        ),
    ]
