# Generated by Django 5.1.3 on 2025-01-25 10:57

import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=index.models.file_name
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-SHOW 1-HIDE"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=150)),
                ("product_vendor", models.CharField(max_length=150)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=index.models.file_name
                    ),
                ),
                ("product_quantity", models.IntegerField()),
                ("original_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("product_description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-SHOW 1-HIDE"),
                ),
                (
                    "trending_product",
                    models.BooleanField(default=False, help_text="0-YES 1-NO"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="index.category"
                    ),
                ),
            ],
        ),
    ]
