# Generated by Django 5.1.3 on 2025-01-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="products",
            new_name="product",
        ),
    ]
