# Generated by Django 5.1.3 on 2025-01-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="new_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=1500),
        ),
    ]
