# Generated by Django 5.1.3 on 2025-01-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_alter_product_brands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brands",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Apple", "Apple"),
                    ("Vivo", "Vivo"),
                    ("Redmi", "Redmi"),
                    ("Oppo", "Oppo"),
                    ("Samsung", "Samsung"),
                    ("Oneplus", "Oneplus"),
                    ("Lenovo", "Lenovo"),
                    ("Dell", "Dell"),
                    ("LG", "LG"),
                    ("Acer", "Acer"),
                    ("Poco", "Poco"),
                    ("HP", "HP"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
